# Generated by Django 3.2.23 on 2024-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPay',
            fields=[
                ('clinic_pay', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'clinic_pay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment', models.AutoField(primary_key=True, serialize=False)),
                ('cardholdername', models.CharField(max_length=45)),
                ('acc_no', models.CharField(max_length=45)),
                ('cvv', models.CharField(max_length=45)),
                ('amount', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacyPayment',
            fields=[
                ('phpayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'pharmacy_payment',
                'managed': False,
            },
        ),
    ]
