# Generated by Django 3.2.23 on 2024-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('phbill_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('qty', models.CharField(max_length=45)),
                ('amount', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'pharmacy_bill',
                'managed': False,
            },
        ),
    ]
